training1/model_form/model_form/urls.py
from django.contrib import admin
from django.urls import path, include
from myTrain import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = 'index' ),
    path('myTrain/', include('myTrain.urls'))
]

training1/model_form/myTrain/urls.py
from django.urls import path
from myTrain import views

app_name = "myTrain"

urlpatterns = [
    path('', views.index, name = "index"),
    path('login/', views.log_in, name = 'login'),
    path('register/', views.register, name = 'register')
]

training1/model_form/myTrain/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Website(models.Model):

    user = models.OneToOneField(User, on_delete = models.CASCADE)
    portfolio = models.URLField(blank = True)

    def __str__(self):
        return self.user.username

training1/model_form/myTrain/forms.py
from django import forms
from django.contrib.auth.models import User
from myTrain.models import Website

class UserInfoForm(forms.ModelForm):

    password = forms.CharField(widget = forms.PasswordInput())

    class Meta():

        model = User
        fields = ("username","email","password")

class UserWebsiteForm(forms.ModelForm):

    class Meta():

        model = Website
        fields = ('portfolio',)

training1/model_form/myTrain/views.py
from django.shortcuts import render
from myTrain.forms import UserInfoForm, UserWebsiteForm
from django.contrib.auth import authenticate, login, logout

from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):

    return render(request, 'myTrain/index.html')

def register(request):

    registered = False

    if request.method == "POST":

        user_form = UserInfoForm(data = request.POST)
        website_form = UserWebsiteForm(data = request.POST)

        if user_form.is_valid() and website_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            website = website_form.save(commit = False)
            website.user = user

            if 'portfolio' in request.POST:
                website.portfolio = request.POST["portfolio"]

            website.save()

            registered = True

    else:

        user_form = UserInfoForm()
        website_form = UserWebsiteForm()        

    return render(request, 'mytrain/register.html', context = {'user_form':user_form,'website':website_form, 'registered':registered})

def log_in(request):

    if request.method == "POST":

        username = request.POST.get('username')

        password = request.POST.get('password')

        user = authenticate(username = username, password = password)

        if user:

            if user.is_active:

                login(request,user)
                print("user is active")
                return HttpResponseRedirect(reverse('index'))

            else:

                return HttpResponse("Something Went Wrong. Did you registered properly?")

        else:

            return HttpResponse("Invalid Credentials")
    
    else:

        return render(request, "myTrain/login.html", {})


@login_required
def log_out(request):

    logout(request)
    return HttpResponseRedirect(reverse('index'))

training1/model_form/templates/myTrain/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "style/base.css" %}">
    <title>Document</title>
</head>
<body>
    <nav class = 'nav'>
        <ul>
            <li>
                <a href="{% url "myTrain:index" %}">Index</a>
            </li>
            <li>
                <a href="{% url "myTrain:login" %}">Login</a>
            </li>
            <li>
                <a href="{% url "myTrain:register" %}">Register</a>
            </li>
        </ul>
    </nav>
    {% block body_block %}
    {% endblock %}
</body>
</html>

training1/model_form/templates/myTrain/index.html
{% extends "myTrain/base.html" %}

    {% block body_block %}
    <h1>Hello, If you're seeing this, its working!</h1>
    {% endblock %}

training1/model_form/templates/myTrain/login.html
{% extends "myTrain/base.html" %}

    {% block body_block %}
        <h1>Welcome to the login page!</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" name="username" placeholder="Enter Username here">
            <label for="password">Password:</label>
            <input type="password" name = "password" placeholder='Password'>
            <input type="submit" value = "Login">
        </form>
    {% endblock %}

training1/model_form/templates/myTrain/register.html
{% extends "myTrain/base.html" %}

{% block body_block %}
    
    {% if not registered %}
    <H2>Welcome to the registration page</H2>
    <form action="" method = "POST">
        {{ user_form.as_p }}
        {{ website.as_p }}
        {% csrf_token %}
    <input type="submit">
    </form>
    {% else %}
    <h2>Thanks for registering! You May now <a href="{% url "myTrain:login" %}">login</a style ="color: green">!</h2>
    {% endif %}
{% endblock %}